# Generated by Django 4.0 on 2025-11-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2news',
            name='comment',
        ),
        migrations.AddField(
            model_name='test2news',
            name='post',
            field=models.TextField(default='', verbose_name='記事本文'),
        ),
        migrations.AlterField(
            model_name='test2news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test2_app.category', verbose_name='カテゴリー'),
        ),
    ]
