# Generated by Django 4.0 on 2025-11-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0002_remove_test2news_comment_test2news_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2news',
            name='image2',
        ),
        migrations.AlterField(
            model_name='test2news',
            name='image1',
            field=models.ImageField(upload_to='photos', verbose_name='タイトル画像'),
        ),
    ]
