# Generated by Django 4.0 on 2025-11-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0004_alter_test2news_image1_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
