# Generated by Django 4.0 on 2025-11-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2_app', '0005_test2news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2news',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='編集が行われた場合にセットされます。', null=True, verbose_name='更新日時'),
        ),
    ]
